name: build

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: pnpm install
      - run: pnpm build
      - run: git config --global user.name "Collight"
      - run: git config --global user.email "collight@hotmail.com"
      - run: npm version ${{ github.event.release.tag_name }} --allow-same-version
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
